/** Generated by itemis CREATE code generator. */

#ifndef STATECHART_REQUIRED_H_
#define STATECHART_REQUIRED_H_

#include "../src/sc_types.h"
#include "Statechart.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- statechart_led_product_selected
- statechart_led_product_selected_off
- statechart_led_credit_on
- statechart_led_credit_off
- statechart_led_dispense_on
- statechart_led_dispense_off
- statechart_print_credit
- statechart_print_product_selected
- statechart_print_no_credit_insert_more_coins
- statechart_print_no_credit_available
- statechart_print_dispensing_product
- statechart_print_please_pick_your_change
- statechart_print_press_any_button_to_proceed
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- never call the statechart API functions from within these functions.
- make sure that the execution time is as short as possible.

*/


extern sc_integer statechart_led_product_selected( Statechart* handle, const sc_integer a);
extern sc_integer statechart_led_product_selected_off( Statechart* handle);
extern sc_integer statechart_led_credit_on( Statechart* handle);
extern sc_integer statechart_led_credit_off( Statechart* handle);
extern sc_integer statechart_led_dispense_on( Statechart* handle);
extern sc_integer statechart_led_dispense_off( Statechart* handle);

extern sc_integer statechart_print_credit( Statechart* handle, const sc_integer credit);
extern sc_integer statechart_print_product_selected( Statechart* handle, const sc_integer select);
extern sc_integer statechart_print_no_credit_insert_more_coins( Statechart* handle);
extern sc_integer statechart_print_no_credit_available( Statechart* handle);
extern sc_integer statechart_print_dispensing_product( Statechart* handle);
extern sc_integer statechart_print_please_pick_your_change( Statechart* handle);
extern sc_integer statechart_print_press_any_button_to_proceed( Statechart* handle);




#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_REQUIRED_H_ */
