/** Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region__Idle_(Statechart* handle);
static void enact_main_region__browsing_(Statechart* handle);
static void enact_main_region__Dispense_(Statechart* handle);
static void enact_main_region__Credit_get_(Statechart* handle);
static void exact_main_region__Dispense_(Statechart* handle);
static void exact_main_region__Credit_get_(Statechart* handle);
static void enseq_main_region__Idle__default(Statechart* handle);
static void enseq_main_region__browsing__default(Statechart* handle);
static void enseq_main_region__Dispense__default(Statechart* handle);
static void enseq_main_region__Credit_get__default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void exseq_main_region__Idle_(Statechart* handle);
static void exseq_main_region__browsing_(Statechart* handle);
static void exseq_main_region__Dispense_(Statechart* handle);
static void exseq_main_region__Credit_get_(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);

/*! State machine reactions. */
static sc_integer react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state <Idle>. */
static sc_integer main_region__Idle__react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state <browsing>. */
static sc_integer main_region__browsing__react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state <Dispense>. */
static sc_integer main_region__Dispense__react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state <Credit_get>. */
static sc_integer main_region__Credit_get__react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);




static void statechart_internal_set_credit(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_select(Statechart* handle, sc_integer value)
;


static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart Statechart */
	statechart_internal_set_credit(handle, 0);
	statechart_internal_set_select(handle, 0);
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region__Idle_ :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION__IDLE_] == Statechart_main_region__Idle_
			);
				break;
		case Statechart_main_region__browsing_ :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION__BROWSING_] == Statechart_main_region__browsing_
			);
				break;
		case Statechart_main_region__Dispense_ :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION__DISPENSE_] == Statechart_main_region__Dispense_
			);
				break;
		case Statechart_main_region__Credit_get_ :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION__CREDIT_GET_] == Statechart_main_region__Credit_get_
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->ifaceBut.coin1_raised = bool_false;
	handle->ifaceBut.coin2_raised = bool_false;
	handle->ifaceBut.browse_raised = bool_false;
	handle->ifaceBut.enter_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region__Idle_ :
		{
			main_region__Idle__react(handle,-1);
			break;
		}
		case Statechart_main_region__browsing_ :
		{
			main_region__browsing__react(handle,-1);
			break;
		}
		case Statechart_main_region__Dispense_ :
		{
			main_region__Dispense__react(handle,-1);
			break;
		}
		case Statechart_main_region__Credit_get_ :
		{
			main_region__Credit_get__react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_but_raise_coin1(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_but_coin1);
	run_cycle(handle);
}

void statechart_but_raise_coin2(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_but_coin2);
	run_cycle(handle);
}

void statechart_but_raise_browse(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_but_browse);
	run_cycle(handle);
}

void statechart_but_raise_enter(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_but_enter);
	run_cycle(handle);
}








static void statechart_internal_set_credit(Statechart* handle, sc_integer value)
{
	handle->internal.credit = value;
}
static void statechart_internal_set_select(Statechart* handle, sc_integer value)
{
	handle->internal.select = value;
}


/* implementations of all internal functions */

/* Entry action for state '<Idle>'. */
static void enact_main_region__Idle_(Statechart* handle)
{
	/* Entry action for state '<Idle>'. */
	statechart_print_press_any_button_to_proceed(handle);
	statechart_led_product_selected_off(handle);
}

/* Entry action for state '<browsing>'. */
static void enact_main_region__browsing_(Statechart* handle)
{
	/* Entry action for state '<browsing>'. */
	statechart_led_product_selected(handle,handle->internal.select);
	statechart_print_credit(handle,handle->internal.credit);
	statechart_print_product_selected(handle,handle->internal.select);
}

/* Entry action for state '<Dispense>'. */
static void enact_main_region__Dispense_(Statechart* handle)
{
	/* Entry action for state '<Dispense>'. */
	statechart_led_dispense_on(handle);
	statechart_internal_set_credit(handle, (handle->internal.credit - handle->internal.select));
	statechart_print_dispensing_product(handle);
}

/* Entry action for state '<Credit_get>'. */
static void enact_main_region__Credit_get_(Statechart* handle)
{
	/* Entry action for state '<Credit_get>'. */
	statechart_led_credit_on(handle);
	statechart_internal_set_credit(handle, 0);
	statechart_print_please_pick_your_change(handle);
}

/* Exit action for state '<Dispense>'. */
static void exact_main_region__Dispense_(Statechart* handle)
{
	/* Exit action for state '<Dispense>'. */
	statechart_led_dispense_off(handle);
}

/* Exit action for state '<Credit_get>'. */
static void exact_main_region__Credit_get_(Statechart* handle)
{
	/* Exit action for state '<Credit_get>'. */
	statechart_led_credit_off(handle);
}

/* 'default' enter sequence for state <Idle> */
static void enseq_main_region__Idle__default(Statechart* handle)
{
	/* 'default' enter sequence for state <Idle> */
	enact_main_region__Idle_(handle);
	handle->stateConfVector[0] = Statechart_main_region__Idle_;
}

/* 'default' enter sequence for state <browsing> */
static void enseq_main_region__browsing__default(Statechart* handle)
{
	/* 'default' enter sequence for state <browsing> */
	enact_main_region__browsing_(handle);
	handle->stateConfVector[0] = Statechart_main_region__browsing_;
}

/* 'default' enter sequence for state <Dispense> */
static void enseq_main_region__Dispense__default(Statechart* handle)
{
	/* 'default' enter sequence for state <Dispense> */
	enact_main_region__Dispense_(handle);
	handle->stateConfVector[0] = Statechart_main_region__Dispense_;
}

/* 'default' enter sequence for state <Credit_get> */
static void enseq_main_region__Credit_get__default(Statechart* handle)
{
	/* 'default' enter sequence for state <Credit_get> */
	enact_main_region__Credit_get_(handle);
	handle->stateConfVector[0] = Statechart_main_region__Credit_get_;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state <Idle> */
static void exseq_main_region__Idle_(Statechart* handle)
{
	/* Default exit sequence for state <Idle> */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state <browsing> */
static void exseq_main_region__browsing_(Statechart* handle)
{
	/* Default exit sequence for state <browsing> */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state <Dispense> */
static void exseq_main_region__Dispense_(Statechart* handle)
{
	/* Default exit sequence for state <Dispense> */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region__Dispense_(handle);
}

/* Default exit sequence for state <Credit_get> */
static void exseq_main_region__Credit_get_(Statechart* handle)
{
	/* Default exit sequence for state <Credit_get> */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region__Credit_get_(handle);
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region__Idle_ :
		{
			exseq_main_region__Idle_(handle);
			break;
		}
		case Statechart_main_region__browsing_ :
		{
			exseq_main_region__browsing_(handle);
			break;
		}
		case Statechart_main_region__Dispense_ :
		{
			exseq_main_region__Dispense_(handle);
			break;
		}
		case Statechart_main_region__Credit_get_ :
		{
			exseq_main_region__Credit_get_(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	statechart_internal_set_credit(handle, 0);
	statechart_internal_set_select(handle, 0);
	enseq_main_region__Idle__default(handle);
}


static sc_integer react(Statechart* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_region__Idle__react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state <Idle>. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->ifaceBut.enter_raised == bool_true)
		{ 
			exseq_main_region__Idle_(handle);
			enseq_main_region__browsing__default(handle);
			react(handle,0);
			transitioned_after = 0;
		}  else
		{
			if (handle->ifaceBut.coin1_raised == bool_true)
			{ 
				exseq_main_region__Idle_(handle);
				handle->internal.credit++;
				enseq_main_region__browsing__default(handle);
				react(handle,0);
				transitioned_after = 0;
			}  else
			{
				if (handle->ifaceBut.coin2_raised == bool_true)
				{ 
					exseq_main_region__Idle_(handle);
					statechart_internal_set_credit(handle, (handle->internal.credit + 2));
					enseq_main_region__browsing__default(handle);
					react(handle,0);
					transitioned_after = 0;
				}  else
				{
					if (handle->ifaceBut.browse_raised == bool_true)
					{ 
						exseq_main_region__Idle_(handle);
						enseq_main_region__browsing__default(handle);
						react(handle,0);
						transitioned_after = 0;
					} 
				}
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_region__browsing__react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state <browsing>. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->ifaceBut.enter_raised) == bool_true) && ((((handle->internal.select) == (0)) && ((handle->internal.credit) != (0))) == bool_true))
		{ 
			exseq_main_region__browsing_(handle);
			enseq_main_region__Credit_get__default(handle);
			react(handle,0);
			transitioned_after = 0;
		}  else
		{
			if (((handle->ifaceBut.enter_raised) == bool_true) && ((((handle->internal.select) > (0)) && ((handle->internal.credit) >= (handle->internal.select))) == bool_true))
			{ 
				exseq_main_region__browsing_(handle);
				enseq_main_region__Dispense__default(handle);
				react(handle,0);
				transitioned_after = 0;
			}  else
			{
				if (((handle->ifaceBut.browse_raised) == bool_true) && (((handle->internal.select) < (3)) == bool_true))
				{ 
					exseq_main_region__browsing_(handle);
					handle->internal.select++;
					enseq_main_region__browsing__default(handle);
					react(handle,0);
					transitioned_after = 0;
				}  else
				{
					if (((handle->ifaceBut.browse_raised) == bool_true) && (((handle->internal.select) == (3)) == bool_true))
					{ 
						exseq_main_region__browsing_(handle);
						statechart_internal_set_select(handle, 0);
						enseq_main_region__browsing__default(handle);
						react(handle,0);
						transitioned_after = 0;
					}  else
					{
						if (((handle->ifaceBut.enter_raised) == bool_true) && ((((handle->internal.select) == (0)) && ((handle->internal.credit) == (0))) == bool_true))
						{ 
							exseq_main_region__browsing_(handle);
							statechart_print_no_credit_available(handle);
							enseq_main_region__browsing__default(handle);
							react(handle,0);
							transitioned_after = 0;
						}  else
						{
							if (((handle->ifaceBut.enter_raised) == bool_true) && ((((handle->internal.select) > (0)) && ((handle->internal.credit) < (handle->internal.select))) == bool_true))
							{ 
								exseq_main_region__browsing_(handle);
								statechart_print_no_credit_insert_more_coins(handle);
								enseq_main_region__browsing__default(handle);
								react(handle,0);
								transitioned_after = 0;
							}  else
							{
								if (handle->ifaceBut.coin1_raised == bool_true)
								{ 
									exseq_main_region__browsing_(handle);
									handle->internal.credit++;
									enseq_main_region__browsing__default(handle);
									react(handle,0);
									transitioned_after = 0;
								}  else
								{
									if (handle->ifaceBut.coin2_raised == bool_true)
									{ 
										exseq_main_region__browsing_(handle);
										statechart_internal_set_credit(handle, (handle->internal.credit + 2));
										enseq_main_region__browsing__default(handle);
										react(handle,0);
										transitioned_after = 0;
									} 
								}
							}
						}
					}
				}
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_region__Dispense__react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state <Dispense>. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->ifaceBut.enter_raised) == bool_true) && (((handle->internal.credit) > (0)) == bool_true))
		{ 
			exseq_main_region__Dispense_(handle);
			enseq_main_region__browsing__default(handle);
			react(handle,0);
			transitioned_after = 0;
		}  else
		{
			if (((handle->ifaceBut.enter_raised) == bool_true) && (((handle->internal.credit) == (0)) == bool_true))
			{ 
				exseq_main_region__Dispense_(handle);
				enseq_main_region__Idle__default(handle);
				react(handle,0);
				transitioned_after = 0;
			} 
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_region__Credit_get__react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state <Credit_get>. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->ifaceBut.enter_raised == bool_true)
		{ 
			exseq_main_region__Credit_get_(handle);
			enseq_main_region__Idle__default(handle);
			react(handle,0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_but_coin1:
		{
			handle->ifaceBut.coin1_raised = bool_true;
			return bool_true;
		}
		case Statechart_but_coin2:
		{
			handle->ifaceBut.coin2_raised = bool_true;
			return bool_true;
		}
		case Statechart_but_browse:
		{
			handle->ifaceBut.browse_raised = bool_true;
			return bool_true;
		}
		case Statechart_but_enter:
		{
			handle->ifaceBut.enter_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
